### ISSUE TITLE
Order of include toolboxes

### ISSUE THREAD

**Issue by DavidBrainard** [ToolboxHub/ToolboxToolbox#19]
Currently "include" toolboxes in a json file are put onto the path after all of the explicitly pointed to toolboxes.  It would be nice if the path order respected the order specified in the json file, independent of the type of toolbox record.

**Comment by benjamin-heasly** [comment]
I agree.

As I recall, they get out of order because an "include" can turn into zero, one, or several "resolved" records.  So it was easier to implement by appending the resolved records to the working set, as opposed to inserting them in place.

But we with some more bookkeeping we can make the final result respect the order that was originally specified.
