### ISSUE TITLE
When tbSystem attempts to do a git pull and git pull prompts for a password, toolbox deployment stalls

### ISSUE THREAD

**Issue by spitschan** [ToolboxHub/ToolboxToolbox#20]
I previously described this issue in the #toolbox_toolbox channel on Slack, but have made some progress understanding the behavior. Recapitulating this below.

- When using `tbUse(...)` on a valid configuration, I would get the following message in the MATLAB command window: `Updating "MRklar".` This message would stay in the command window until I pressed enter. Then, the same thing would happen with the next toolbox.
- The reason why this stalls is because the method `systemInFolder` in `TbGitStrategy` sometimes encounters calls to `git pull` which prompt the user for a password. Pressing enter would then function as the password.
- This is the case on the Linux cluster in which this has occurred. I'm not sure this is because I had previously manually set up the toolboxes.

**Comment by spitschan** [comment]
Not sure if this would be related, but the git version on the cluster is also from 2010:

```
$ git --version
git version 1.7.1
```

**Comment by spitschan** [comment]
This also seems to be a problem on systems where the git configuration relies on SSH and the computer you're using doesn't have the github ssh key yet.

```
>> tbUse('fmriMelanopsinMRIAnalysis')
Updating "ToolboxRegistry".
Updating "MRklar".
Updating "MRlyze".
Obtaining "temporalFittingEngine".
Adding "ToolboxToolbox" to path at "/Users/mspits/Documents/MATLAB/Toolboxes/ToolboxToolbox".
Adding "MRklar" to path at "/Users/mspits/Documents/MATLAB/Toolboxes/MRklar".
Adding "MRlyze" to path at "/Users/mspits/Documents/MATLAB/Toolboxes/MRlyze".
Error: "temporalFittingEngine" had status 128, message "Cloning into '/Users/mspits/Documents/MATLAB/Toolboxes/temporalFittingEngine'...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? 
Host key verification failed.
```

I had to press enter after waiting for ~20 secs to even see that message.

**Comment by benjamin-heasly** [comment]
I think there are two issues lurking here.  Here's how I understand them--

First is if you already cloned a private repo over https, and that repo requires a password, then TbTb will hang on the update because it doesn't know how to be interactive and ask the user for a password.

The work-around I recommend for now is to clone over ssh instead of https.  Which leads to...

Second, if you are cloning or updating over ssh, and the machine hasn't yet accepted GitHub's certificate, then TbTb will hang waiting for the user to type "yes" to accept the certificate.

I guess a work-around for now would be to clone one repository over ssh manually from the terminal, and type "yes" to accept the certificate.  Then after that, TbTb should be able to proceed non-interactively for other repos.

It would be great if we could make these "just work" instead of having to work around them.  Some ideas:
  - I wonder if there's a way to get Matlab to prompt for input in the middle of a `system` or `!` command?
  - I wonder if there's a flag we can pass to git clone to say "yes" automatically, similar to the "y" flag for apt-get.
  - If a toolbox record had a field for "requires password", this would give TbTb a hint that it should prompt for a password before doing clone or update.

**Comment by spitschan** [comment]
I believe this is fixed by running `system(command, '-echo)` instead of `system(command)`. Here's the quote from the MATLAB help:

"[status,cmdout] = system(command,'-echo') also displays (echoes) the command output in the MATLAB® Command Window. This syntax is most useful for commands that require user input and that run correctly in the MATLAB Command Window." (https://www.mathworks.com/help/matlab/ref/system.html)

However, it also seems to produce a bunch of white space.

**Comment by spitschan** [comment]
This addresses the first point – "I wonder if there's a way to get Matlab to prompt for input in the middle of a system or ! command?".

**Comment by spitschan** [comment]
Regarding your second question – 

> _"I wonder if there's a flag we can pass to git clone to say "yes" automatically, similar to the "y" flag for apt-get."_

I'm not sure if that's a good idea since we don't just want to randomly accept ssh certificates?

**Comment by benjamin-heasly** [comment]
Ha!  So simple.  I didn't know system() had this option.  Thanks for RTFM and the PR.

Do you think we should make the echo optional, in case we can find places where it makes sense to suppress the verbose output?

**Comment by benjamin-heasly** [comment]
Re the second idea about automatically accepting certificates, I think you're right, we should not randomly accept them.

**Comment by spitschan** [comment]
Making the `-echo` flag optional seems appropriate. How would that be set up?

**Comment by gkaguirre** [comment]
Manuel -- at this stage do you have TbTb working on the cluster?

**Comment by spitschan** [comment]
Yes, it's working but I typically do most of the git business outside of MATLAB.

**Comment by benjamin-heasly** [comment]
Merged the change so we can do system commands interactively.  So I think this is fixed?

Please re-open if it's not really fixed.
