### ISSUE TITLE
Organization of configuration files

### ISSUE THREAD

**Issue by DavidBrainard** [ToolboxHub/ToolboxToolbox#24]
As the number of configuration files grows, we may want to set up some sort of hierarchical directory.  For example, I just figured out how to set up a TbTb file for a toolbox available on Matlab central.  We might want to have a subfolder just for these, which would then be natural to use as "include" toolboxes in project configurations that need them.

Similarly, we will probably want to distinguish toolboxes from projects once we implement that dichotomy. 

And possible have some subfolders to help us organize both projects and toolboxes.

**Comment by gkaguirre** [comment]
Perhaps something like `Toolboxes/MatlabCentral/item/item.m`, where `item` is the matlab central file name, allowing one to move these in and out of the path.

**Comment by benjamin-heasly** [comment]
I think it would be good to organize the configuration files.  But I would like to be cautious about using the folder hierarchy for this.

Here's my thinking (plus some cats and frogs) --
 
:cat2: Adding folders would complicate the code, since `tbUse('name')` would have to do a recursive search for `name`, instead of just checking whether a `name.json` exists in a certain folder.

:cat2: With folders, it would take extra effort to make sure that configuration names are unique, since the same file name could exist in multiple folders.  This would make `tbUse('name')` ambiguous, or even unstable as configuration files and folders were added over time.

For example, what if someone else adds a new `name.json` to a folder that comes up first during the recursive search?  Suddenly `tbUse('name')` would pull down a different config.

:cat2: With folders, we only get one hierarchy with which to organize things.  I'm not sure that one hierarchy will be right for everyone.  I also don't want to commit early to a scheme that we decide is wrong, and then spend time rearranging folders in the registry.

One reason I think choosing the right scheme would be hard is that configuration files can contain multiple toolboxes.  What if they don't all fit nicely into the same subfolder?

:cat2: To distinguish toolboxes from projects, I think using folders might be good.  But then I think this should be the only way that we distinguish them.  For example, we should not also have a field of toolbox records that stores the same information.  I think this would invite confusion of the form, "Why is this project sitting in the toolbox folder?"

:frog: As an alternative to the folder hierarchy, I suggest we work on search tools for the registry.  GitHub already gives us a "crappy" way to do text search in the registry repo: here are the [webget](https://github.com/ToolboxHub/ToolboxRegistry/search?l=json&q=webget&utf8=%E2%9C%93) configurations, and here are the [git](https://github.com/ToolboxHub/ToolboxRegistry/search?l=json&q=git&utf8=%E2%9C%93) ones.   We could think about ways to improve this.

:frog: We could also add tools on the Matlab client side for searching or viewing what's in the registry.

**Comment by DavidBrainard** [comment]
Obsolete because we now know about projects.
