### ISSUE TITLE
Spurious warnings

### ISSUE THREAD

**Issue by DavidBrainard** [ToolboxHub/ToolboxToolbox#3]
I get this warning after doing a tbUse( ,'reset','all')

Warning: Support for ver('fixpoint') will be removed in a future release.  Use ver('fixedpoint') instead. 
> In ver>locGetSingleToolboxInfo (line 279)
  In ver (line 52)
  In tbResetMatlabPath (line 78)
  In tbDeployToolboxes (line 127)
  In tbUse (line 51)

This is probably a MATLAB version dependent thing, but it would be nice to avoid it and/or suppress it.  Warnings like this reduce user confidence that things are OK.

As an aside, I think we should in general support the last two years of Matlab releases and not worry about versions before that.  So right now, 2014a and later.

**Comment by benjamin-heasly** [comment]
Yes, I think that is version-dependent.  It looks like both toolbox folders exist, `fixedpoint`, which is apparently the one we want, and `fixpoint` which is apparently deprecated.

What's annoying is that we didn't write "fixpoint" anywhere in our code.  We're only trying to remove it because Matlab reported it to us as a toolbox folder.

I think what we can do is turn off the warning `MATLAB:ver:ProductNameDeprecated`.  And also mumble some curses.

**Comment by DavidBrainard** [comment]
Sounds like a good way to go.

DB

**Comment by benjamin-heasly** [comment]
This change is in.  It LGTM on local machine and GPC cluster.
