### ISSUE TITLE
tbUse usage

### ISSUE THREAD

**Issue by DavidBrainard** [ToolboxHub/ToolboxToolbox#4]
I think it would be nice if one could type either tbUse('MyConfig',...) or tbUse({'MyConfig'}, ...).  I usually just have one config arg, and remembering to put in the brackets is a little annoying.  Keeping the list usage also seems good.

**Comment by benjamin-heasly** [comment]
I agree with this.  I'll make the change.

Just to be concrete, the new syntax will only work with a single toolbox name.

What we can do now for a single toolbox name is
```tbUse({'foo'}, ...)```

or for a list of names
```tbUse({'foo', 'bar', ...}, ...)```

I'll add a new way to do a single toolbox name
```tbUse('foo', ...)```

But I won't try to add a new way to do a list of names
```tbUse('foo', 'bar', ...)```

because that would make the toolbox names hard to distinguish from other parameters to `tbUse()`.

**Comment by DavidBrainard** [comment]
Yes, what you describe is exactly what I had in mind.

DB

**Comment by benjamin-heasly** [comment]
This change is in. It LGTM on local machine and GPC cluster.
