### ISSUE TITLE
unable to change current dir using local hook and tbUseProject

### ISSUE THREAD

**Issue by gkaguirre** [ToolboxHub/ToolboxToolbox#63]
I would like my local hook to change the current directory. The file contains this:

> % Find the project directory, add it to the path, save this as a
> %  pref, and then make this the current directory
> projectDir = fullfile(tbLocateProject('myProject'));
> addpath(genpath(projectDir));
> setpref('surveyMelanopsinAnalysis', 'projectDir', projectDir);
> cd(projectDir);

When executed during the call to tbUseProject, the `addpath` and `setpref` steps complete, but there is no change in directory. When run directly, however, the local hook does change the directory.

**Comment by benjamin-heasly** [comment]
Aha!  This was sort of intentional.

The code attempts to keep hooks isolated from each other by making them run in separate workspaces and by changing back to the original directory after each hook finishes.  Here is where that happens in [tbDeployToolboxes](https://github.com/ToolboxHub/ToolboxToolbox/blob/master/api/tbDeployToolboxes.m#L284).

My intention with isolating the hooks in this way was to avoid hard-to-debug errors that depend on the order of hook execution or Matlab state like variables in the base workspace or the current value of `pwd()`.

But maybe this is unnecessary or impractical.  I am open to doing it differently.

@gkaguirre @DavidBrainard -- Do you think `cd()` from local hooks is something we ought to support?  Or would it be enough to update the docs and print statements to make current behavior is less confusing?

**Comment by gkaguirre** [comment]
Gotcha. Given that you cannot guarantee the order in which the local hook runs with regard to hooks called from various toolboxes, I can understand this limitation.

It's obvious to the user that the directory has not changed, so I think a note in the documentation indicating that this is not a bug would be enough.

**Comment by DavidBrainard** [comment]
It's possible that good default (or optional) behavior for projects would be to have tbUseProject leave the cwd to be the project directory.  This could then, I suppose, be overridden (or turned on) in a key-value pair to the tbUseProject function.

**Comment by gkaguirre** [comment]
That default behavior sounds sensible.

**Comment by DavidBrainard** [comment]
We will implement this default behavior, with an option to pass an argument to turn it off.

**Comment by benjamin-heasly** [comment]
Cool.

I added a note to the wiki about this: [hook-isolation](https://github.com/ToolboxHub/ToolboxToolbox/wiki/Local-Hooks#hook-isolation).

I also made #64 which adds the new `cd()` behavior.  I'll merge after the tests pass.
