### ISSUE TITLE
Trouble with a Matlab configuration

### ISSUE THREAD

**Issue by gkaguirre** [ToolboxHub/ToolboxToolbox#65]
I am following the example Matlab Central json configuration:

https://github.com/ToolboxHub/ToolboxRegistry/blob/master/configurations/matlabcentral-demo.json

and have created this entry:

> 	{
>		"flavor": "",
>		"hook": "",
>		"importance": "",
>		"localHookTemplate": "",
>		"name": "TheilSen",
>		"pathPlacement": "append",
>		"subfolder": "",
>		"toolboxRoot": "",
>		"type": "webget",
>		"update": "never",
>		"url": "https://www.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/48294/versions/4/download/zip"
>	}

TbTb recognizes this as well formed and attempts to download the repository. The result, however, is a directory in my toolbox folder with the appropriate name, but containing just a file called `zip` (which also happens to be malformed and cannot be unzipped). I have confirmed that, when entered in a browser, the url downloads a file named `ThielSen.zip`.

Am I doing something obviously wrong?

**Comment by DavidBrainard** [comment]
I think you are doing it right.  The example now has the same problem (if you first delete the toolbox).  This looks like a problem in how the webget command is invoked, or how the URL is parsed.

**Comment by benjamin-heasly** [comment]
Hi @gkaguirre,

I recently encountered this, too.  I am not sure why this stopped working.  Possibly Mathworks changed how they serve the files, and the zips are not longer recognized.

Will it work if you change the `flavor` to `zip`?  This should force ToolboxToolbox to treat whatever it gets as a zip, and unzip it.  There's slight mention of this behavior on the [wiki](https://github.com/ToolboxHub/ToolboxToolbox/wiki/Toolbox-Records-and-Types#webget).

If this works, then probably we should update the example...

**Comment by gkaguirre** [comment]
@benjamin-heasly: The change in flavor worked, with the following caveats:
1) The name of the created directory within `toolboxes` is `TheilSen_zip`. Perhaps this is the desired behavior.
2) Within the directory `TheilSen_zip`, there are these files:
> zip
> license.txt
> TheilSen.m
The last two are appropriate and well formed. The first is the zip file for the repository, but lacking the full file name. If I change its name from `zip --> myTest.zip` I can then unzip `myTest` and it appropriately contains code and license files.

Thanks again for the fix.

**Comment by DavidBrainard** [comment]
I updated TbTb to special case Matlab central URLs, so that things will work without making the flavor 'zip' and so that the downloaded zip file will have an interpretable name inside the folder.  I recommend getting rid of the 'zip' in the 'flavor' field, although I think things will still work even if you keep it. (But there will be an '_zip' in the directory name and the downloaded zip file will be called Foo.zip.zip rather than Foo.zip in this case.)

I added a note to the wiki about this special case.

Post back here if this seems to be working and we can then close this issue.

**Comment by gkaguirre** [comment]
I pulled the TbTb updates, deleted the ThielSen toolbox, and modified my .json file to set flavor to "".

When deployed, TbTb does the right thing, creating the directory "ThielSen" in my toolboxes directory, with the following contents:
> TheilSen.zip.zip
> license.txt
> TheilSen.m

I think the extra zip was undesired.

**Comment by gkaguirre** [comment]
A separate thought: As long as you are special casing Matlab Central, how about storing all Matlab Central repos within a special purpose directory within `toolboxes`? Perhaps this can be configured using the `toolboxRoot` entry in the .json file, but as I understand it I would have to hard-code the entire path to where the repo should be stored, instead of being able to provide a relative path to a directory within the default location.

**Comment by DavidBrainard** [comment]
I will look into preventing the extra .zip and see if I can figure out how to do the subfolder.  It might make sense if we're going that far to have a separate, explict, 'matlabcentral' type and corresponding strategy.  I think I know how to make that happen.

**Comment by DavidBrainard** [comment]
I fixed the extra zip in the output name and also changed the code so that packages from matlabcentral go into a subdir under toolboxes called matlabcentral.

I did not make this a separate strategy, which would be clearer.  But I did have fun overriding a default method to make this work.

Assuming it works, you should delete the old copy of the relevant toolboxes that are at the top level (not inside the matlabcentral subdir.)

**Comment by gkaguirre** [comment]
This worked perfectly. It's a very nice addition.
