### ISSUE TITLE
Detect changes in local hook template

### ISSUE THREAD

**Issue by gkaguirre** [ToolboxHub/ToolboxToolbox#92]
I not infrequently encounter the circumstance that code failure is the result of dependency upon an updated version of the local hook template file, and that I have failed to delete my local hook copy.

It would be ideal if the local copy of the local hook file was somehow aware of the git version from which it was derived. And that TbTb could warn the user if the local hook template had changed since this version.

I don't have a specific proposal yet of a way to implement this. Just wanted to start the wheels turning.

**Comment by DavidBrainard** [comment]
I don't think it's easy to do this with git version, because the local copies of the local hooks are not versioned.

But, it is easy to check whether the template local hook has a modification date more recent than the local local hook, and I think that is what we want.  I now print out a red message from the tbUse/tbUseProject commands when this happens. I think this will have pretty high but not perfect reliability.

I don't want to auto copy in this case because in principle the local local hook could have local modifications.

It would be possible to get a false alarm if you deleted your local copy of the toolbox or project without deleting the local local hook, because on re-check out the mod dates on the file system match the check out time.  But this would be a rare case and easy enough to fix.

Closing, but re-open and post back if it doesn't seem to be behaving well.
