### ISSUE TITLE
Accept PRQ with Matlab 2016b features?

### ISSUE THREAD

**Issue by githubkusi** [ToolboxHub/ToolboxToolbox#95]
Would you accept a pull request which adds features of Matlab 2016b? Particularly the string class?

**Comment by DavidBrainard** [comment]
If you can write it using ver, so that current functionality doesn't break for earlier versions that would be OK.  That is, I'd like to stay backwards compatible to 2015b for another year or so, but it would be fine to have something new available only in more recent versions.

Even better, I suppose, is if you can write a workaround for earlier versions that we would eventually drop. But I understand that that might defeat the point of using the new functionality.

**Comment by githubkusi** [comment]
Fair enough. I had to abuse "Issues" as a discussion platform. Closing the issue now since you provided the information I need.
